-- Cardio & Free-Workouts: Outdoor / Bodyweight / freie Gewichte
WITH pkg AS (SELECT id FROM packages WHERE slug='cardio_free')
INSERT INTO exercises (slug, package_id, name_key, category, modality, met_value, default_intensity)
SELECT s, (SELECT id FROM pkg), k, c, m, mv, di
FROM (VALUES
  ('cf_running_outdoor',  'exercise.cf_running_outdoor',  'cardio',  'cardio',     9.8, 1.00),
  ('cf_cycling_outdoor',  'exercise.cf_cycling_outdoor',  'cardio',  'cardio',     7.5, 1.00),
  ('cf_swimming',         'exercise.cf_swimming',         'cardio',  'cardio',     8.0, 1.00),
  ('cf_jump_rope',        'exercise.cf_jump_rope',        'cardio',  'cardio',    11.0, 1.00),
  ('cf_burpees',          'exercise.cf_burpees',          'cardio',  'bodyweight', 8.0, 1.00),
  ('cf_jumping_jacks',    'exercise.cf_jumping_jacks',    'cardio',  'bodyweight', 7.0, 1.00),
  ('cf_pushup',           'exercise.cf_pushup',           'strength','bodyweight', 5.0, 0.90),
  ('cf_pullup',           'exercise.cf_pullup',           'strength','bodyweight', 6.0, 1.00),
  ('cf_dip',              'exercise.cf_dip',              'strength','bodyweight', 5.5, 0.95),
  ('cf_bodyweight_squat', 'exercise.cf_bodyweight_squat', 'strength','bodyweight', 5.0, 0.90),
  ('cf_lunge',            'exercise.cf_lunge',            'strength','bodyweight', 5.0, 0.90),
  ('cf_plank',            'exercise.cf_plank',            'strength','bodyweight', 3.5, 0.80),
  ('cf_situp',            'exercise.cf_situp',            'strength','bodyweight', 4.0, 0.85),
  ('cf_kettlebell_swing', 'exercise.cf_kettlebell_swing', 'strength','freeweight', 9.0, 1.10),
  ('cf_db_bench_press',   'exercise.cf_db_bench_press',   'strength','freeweight', 6.0, 1.00),
  ('cf_db_row',           'exercise.cf_db_row',           'strength','freeweight', 6.0, 1.00),
  ('cf_db_curl',          'exercise.cf_db_curl',          'strength','freeweight', 5.0, 0.90),
  ('cf_barbell_squat',    'exercise.cf_barbell_squat',    'strength','freeweight', 6.5, 1.15),
  ('cf_barbell_deadlift', 'exercise.cf_barbell_deadlift', 'strength','freeweight', 7.0, 1.15),
  ('cf_overhead_press',   'exercise.cf_overhead_press',   'strength','freeweight', 6.0, 1.00),
  ('cf_stretching',       'exercise.cf_stretching',       'mobility','bodyweight', 2.3, 0.70)
) AS x(s, k, c, m, mv, di)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO i18n (key, locale, value) VALUES
('exercise.cf_running_outdoor',  'de', 'Joggen (draußen)'),
('exercise.cf_cycling_outdoor',  'de', 'Radfahren (draußen)'),
('exercise.cf_swimming',         'de', 'Schwimmen'),
('exercise.cf_jump_rope',        'de', 'Seilspringen'),
('exercise.cf_burpees',          'de', 'Burpees'),
('exercise.cf_jumping_jacks',    'de', 'Hampelmann'),
('exercise.cf_pushup',           'de', 'Liegestütz'),
('exercise.cf_pullup',           'de', 'Klimmzug'),
('exercise.cf_dip',              'de', 'Dip'),
('exercise.cf_bodyweight_squat', 'de', 'Kniebeuge ohne Gewicht'),
('exercise.cf_lunge',            'de', 'Ausfallschritt'),
('exercise.cf_plank',            'de', 'Unterarmstütz (Plank)'),
('exercise.cf_situp',            'de', 'Sit-up'),
('exercise.cf_kettlebell_swing', 'de', 'Kettlebell Swing'),
('exercise.cf_db_bench_press',   'de', 'Kurzhantel-Bankdrücken'),
('exercise.cf_db_row',           'de', 'Kurzhantel-Rudern'),
('exercise.cf_db_curl',          'de', 'Kurzhantel-Curl'),
('exercise.cf_barbell_squat',    'de', 'Langhantel-Kniebeuge'),
('exercise.cf_barbell_deadlift', 'de', 'Langhantel-Kreuzheben'),
('exercise.cf_overhead_press',   'de', 'Schulterdrücken (Langhantel)'),
('exercise.cf_stretching',       'de', 'Dehnen / Stretching')
ON CONFLICT (key, locale) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO exercise_muscles (exercise_id, muscle_id, involvement)
SELECT (SELECT id FROM exercises WHERE slug=e), (SELECT id FROM muscles WHERE slug=m), inv
FROM (VALUES
  ('cf_running_outdoor','rectus_femoris','primary'),
  ('cf_running_outdoor','biceps_femoris','primary'),
  ('cf_running_outdoor','gastrocnemius','primary'),
  ('cf_running_outdoor','gluteus_maximus','secondary'),
  ('cf_running_outdoor','soleus','secondary'),
  ('cf_cycling_outdoor','rectus_femoris','primary'),
  ('cf_cycling_outdoor','vastus_lateralis','primary'),
  ('cf_cycling_outdoor','gluteus_maximus','secondary'),
  ('cf_cycling_outdoor','gastrocnemius','secondary'),
  ('cf_swimming','latissimus_dorsi','primary'),
  ('cf_swimming','pectoralis_major','primary'),
  ('cf_swimming','deltoideus_anterior','primary'),
  ('cf_swimming','triceps_brachii','secondary'),
  ('cf_swimming','rectus_femoris','secondary'),
  ('cf_swimming','rectus_abdominis','stabilizer'),
  ('cf_jump_rope','gastrocnemius','primary'),
  ('cf_jump_rope','soleus','primary'),
  ('cf_jump_rope','rectus_femoris','secondary'),
  ('cf_burpees','pectoralis_major','primary'),
  ('cf_burpees','rectus_femoris','primary'),
  ('cf_burpees','gluteus_maximus','primary'),
  ('cf_burpees','triceps_brachii','secondary'),
  ('cf_burpees','rectus_abdominis','secondary'),
  ('cf_jumping_jacks','gastrocnemius','primary'),
  ('cf_jumping_jacks','deltoideus_lateralis','secondary'),
  ('cf_pushup','pectoralis_major','primary'),
  ('cf_pushup','triceps_brachii','primary'),
  ('cf_pushup','deltoideus_anterior','secondary'),
  ('cf_pushup','serratus_anterior','stabilizer'),
  ('cf_pushup','rectus_abdominis','stabilizer'),
  ('cf_pullup','latissimus_dorsi','primary'),
  ('cf_pullup','biceps_brachii','primary'),
  ('cf_pullup','teres_major','secondary'),
  ('cf_pullup','rhomboideus','secondary'),
  ('cf_pullup','flexor_carpi','stabilizer'),
  ('cf_dip','triceps_brachii','primary'),
  ('cf_dip','pectoralis_major','primary'),
  ('cf_dip','deltoideus_anterior','secondary'),
  ('cf_bodyweight_squat','rectus_femoris','primary'),
  ('cf_bodyweight_squat','vastus_lateralis','primary'),
  ('cf_bodyweight_squat','gluteus_maximus','primary'),
  ('cf_bodyweight_squat','biceps_femoris','secondary'),
  ('cf_lunge','rectus_femoris','primary'),
  ('cf_lunge','gluteus_maximus','primary'),
  ('cf_lunge','biceps_femoris','secondary'),
  ('cf_lunge','gluteus_medius','stabilizer'),
  ('cf_plank','rectus_abdominis','primary'),
  ('cf_plank','transversus_abdominis','primary'),
  ('cf_plank','obliquus_externus','secondary'),
  ('cf_plank','erector_spinae','stabilizer'),
  ('cf_situp','rectus_abdominis','primary'),
  ('cf_situp','obliquus_externus','secondary'),
  ('cf_situp','iliopsoas','secondary'),
  ('cf_kettlebell_swing','gluteus_maximus','primary'),
  ('cf_kettlebell_swing','biceps_femoris','primary'),
  ('cf_kettlebell_swing','erector_spinae','primary'),
  ('cf_kettlebell_swing','deltoideus_anterior','secondary'),
  ('cf_kettlebell_swing','rectus_abdominis','stabilizer'),
  ('cf_db_bench_press','pectoralis_major','primary'),
  ('cf_db_bench_press','triceps_brachii','secondary'),
  ('cf_db_bench_press','deltoideus_anterior','secondary'),
  ('cf_db_row','latissimus_dorsi','primary'),
  ('cf_db_row','rhomboideus','primary'),
  ('cf_db_row','biceps_brachii','secondary'),
  ('cf_db_row','trapezius_middle','secondary'),
  ('cf_db_row','deltoideus_posterior','secondary'),
  ('cf_db_curl','biceps_brachii','primary'),
  ('cf_db_curl','brachialis','secondary'),
  ('cf_db_curl','brachioradialis','secondary'),
  ('cf_barbell_squat','rectus_femoris','primary'),
  ('cf_barbell_squat','vastus_lateralis','primary'),
  ('cf_barbell_squat','vastus_medialis','primary'),
  ('cf_barbell_squat','gluteus_maximus','primary'),
  ('cf_barbell_squat','erector_spinae','secondary'),
  ('cf_barbell_squat','biceps_femoris','secondary'),
  ('cf_barbell_deadlift','erector_spinae','primary'),
  ('cf_barbell_deadlift','gluteus_maximus','primary'),
  ('cf_barbell_deadlift','biceps_femoris','primary'),
  ('cf_barbell_deadlift','semitendinosus','primary'),
  ('cf_barbell_deadlift','trapezius_middle','secondary'),
  ('cf_barbell_deadlift','latissimus_dorsi','secondary'),
  ('cf_barbell_deadlift','flexor_carpi','stabilizer'),
  ('cf_overhead_press','deltoideus_anterior','primary'),
  ('cf_overhead_press','deltoideus_lateralis','primary'),
  ('cf_overhead_press','triceps_brachii','secondary'),
  ('cf_overhead_press','trapezius_upper','secondary'),
  ('cf_stretching','biceps_femoris','primary'),
  ('cf_stretching','rectus_femoris','primary'),
  ('cf_stretching','gastrocnemius','secondary'),
  ('cf_stretching','latissimus_dorsi','secondary')
) AS m(e, m, inv)
ON CONFLICT (exercise_id, muscle_id) DO NOTHING;
